/**
 * Activity log action types
 */
export const LogAction = {
  // Authentication events
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  PASSWORD_RESET_REQUEST: 'PASSWORD_RESET_REQUEST',
  PASSWORD_RESET_COMPLETE: 'PASSWORD_RESET_COMPLETE',
  ACCOUNT_SETUP_COMPLETE: 'ACCOUNT_SETUP_COMPLETE',
  
  // Form submissions
  DISCOVERY_FORM_SUBMIT: 'DISCOVERY_FORM_SUBMIT',
  CONTACT_FORM_SUBMIT: 'CONTACT_FORM_SUBMIT',
  ASSESSMENT_SUBMIT: 'ASSESSMENT_SUBMIT',
  GEAR_DRIVE_SUBMIT: 'GEAR_DRIVE_SUBMIT',
  
  // Transactions
  ORDER_CREATED: 'ORDER_CREATED',
  ORDER_UPDATED: 'ORDER_UPDATED',
  PAYMENT_COMPLETED: 'PAYMENT_COMPLETED',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  DONATION_COMPLETED: 'DONATION_COMPLETED',
  
  // Admin actions
  USER_CREATED: 'USER_CREATED',
  USER_UPDATED: 'USER_UPDATED',
  USER_DELETED: 'USER_DELETED',
  PACKET_CREATED: 'PACKET_CREATED',
  PACKET_UPDATED: 'PACKET_UPDATED',
  PACKET_PUBLISHED: 'PACKET_PUBLISHED',
  PACKET_UNPUBLISHED: 'PACKET_UNPUBLISHED',
  PRODUCT_CREATED: 'PRODUCT_CREATED',
  PRODUCT_UPDATED: 'PRODUCT_UPDATED',
  PRODUCT_DELETED: 'PRODUCT_DELETED',
  PROGRAM_CREATED: 'PROGRAM_CREATED',
  PROGRAM_UPDATED: 'PROGRAM_UPDATED',
  PROGRAM_DELETED: 'PROGRAM_DELETED',
  CLIENT_NOTE_CREATED: 'CLIENT_NOTE_CREATED',
  CLIENT_ASSIGNED: 'CLIENT_ASSIGNED',
  
  // Content management
  TESTIMONIAL_CREATED: 'TESTIMONIAL_CREATED',
  TESTIMONIAL_UPDATED: 'TESTIMONIAL_UPDATED',
  TESTIMONIAL_PUBLISHED: 'TESTIMONIAL_PUBLISHED',
  IMPACT_AREA_UPDATED: 'IMPACT_AREA_UPDATED',
  
  // Library management
  EXERCISE_CREATED: 'EXERCISE_CREATED',
  EXERCISE_UPDATED: 'EXERCISE_UPDATED',
  NUTRITION_CREATED: 'NUTRITION_CREATED',
  NUTRITION_UPDATED: 'NUTRITION_UPDATED',
} as const

export type LogActionType = typeof LogAction[keyof typeof LogAction]

/**
 * Resource types for activity logs
 */
export const LogResource = {
  AUTH: 'AUTH',
  USER: 'USER',
  DISCOVERY: 'DISCOVERY',
  CONTACT: 'CONTACT',
  ASSESSMENT: 'ASSESSMENT',
  PACKET: 'PACKET',
  ORDER: 'ORDER',
  PAYMENT: 'PAYMENT',
  DONATION: 'DONATION',
  GEAR_DRIVE: 'GEAR_DRIVE',
  PRODUCT: 'PRODUCT',
  PROGRAM: 'PROGRAM',
  CLIENT: 'CLIENT',
  TESTIMONIAL: 'TESTIMONIAL',
  IMPACT_AREA: 'IMPACT_AREA',
  EXERCISE: 'EXERCISE',
  NUTRITION: 'NUTRITION',
} as const

export type LogResourceType = typeof LogResource[keyof typeof LogResource]
